"use strict";
exports.__esModule = true;
var Movie_1 = require("./Movie");
var movieview_1 = require("./movieview");
var movObj = [];
var m1 = new Movie_1.Movie('Your Name', 'Makoto Shinkai', 300000, 4.6, 'Japanese');
var m2 = new Movie_1.Movie('Spirited Away', 'Hayao Miyazaki', 600000, 4.7, 'Japanese');
var m3 = new Movie_1.Movie('Tenent', 'Christopher Nolan', 500000, 3.9, 'English');
var m4 = new Movie_1.Movie('John Wick', 'Chad Stahelski', 700000, 4.1, 'English');
var m5 = new Movie_1.Movie('Dear Zindagi', 'Gauri Shinde', 200000, 4.2, 'Hindi');
var m6 = new Movie_1.Movie('Andhadhun', 'Sriram Raghavan', 150000, 3.8, 'Hindi');
movObj.push(m1);
movObj.push(m2);
movObj.push(m3);
movObj.push(m4);
movObj.push(m5);
movObj.push(m6);
console.log("----------------------");
// m1.movieDetails();
// m2.movieDetails();
// m3.movieDetails();
movieview_1.movieview.movieByLanguage(movObj, 'Japanese');
console.log("----------------------");
movieview_1.movieview.movieByRating(movObj, 4);
